# Generated by Django 4.2.22 on 2025-06-10 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("datetime_ist", models.DateTimeField()),
                ("instructor", models.CharField(max_length=100)),
                ("available_slots", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "classes",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.fitnessclass",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
            },
        ),
    ]
